[package]
name = "rgb"
version = "0.2.0"
license = "MIT"
authors = ["Dr Maxim Orlovsky <dr.orlovsky@gmail.com>"]
description = "Library for working with assets issued on top of Bitcoin and Lightning Network using RGB protocol"
keywords = [ "crypto", "bitcoin", "lightning", "rgb", "tokens" ]
readme = "README.md"
edition = "2018"

[lib]
name = "rgb"
path = "src/lib.rs"

[dependencies]
bitcoin = "~0.18.0"
bech32 = "~0.6.0"
bitcoin-bech32 = "~0.9.0"
bitcoin_hashes = "~0.3.0"

[dependencies.secp256k1]
version = "~0.13.0"
features = [ "rand" ]
